
# See https://medium.com/swlh/setting-up-github-actions-for-go-project-ea84f4ed3a40


# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# on:
#   push:
#     branches:
#     - master
#     - staging
#     - develop
#   pull_request:
#     branches:
#     - master
#     - staging
#     - develop

# Triggers the workflow on push or pull request events
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        # go-version: '1.14.0' # The Go version to download (if necessary) and use.
        go-version: '1.16' # The Go version to use.
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        go get -t -v ./...

    # Run build of the application
    - name: Run build
      run: go build . 
      
    # Run vet & lint on the code
    - name: Run vet & lint
      run: |
        go vet .
        golint .
    
    # Run testing on the code
    - name: Run testing
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic
    #   run: go test -v
    #   run: cd test && go test -v

    - name: Codecov
      uses: codecov/codecov-action@v1.4.0
      with:
        file: ./coverage.txt
        # fail_ci_if_error: true # optional (default = false)
        # verbose: true # optional (default = false)

    # # Send slack notification
    # - name: Send slack notification
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     status: ${{ job.status }}
    #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
    #   if: always() # Pick up events even if the job fails or is canceled.

#   # The "deploy" workflow
#   deploy:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
#     needs: [build] # Only run this workflow when "build" workflow succeeds
#     if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} # Only run this workflow if it is master branch on push event
#     steps:
#     - uses: actions/checkout@v2

#     # Deploy to Docker registry
#     - name: Deploy to Docker registry
#       uses: docker/build-push-action@v1
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
#         repository: wilsontanwm/gosimple
#         tag_with_ref: true


#- name: Codecov
#  uses: codecov/codecov-action@v1.4.0
